In [5]:
class matrix_factorization():

    def __init__(self,data,features):
        import numpy as np
        self.data = data
        self.features = features
        self.L_count = data.shape[0]
        self.U_count = data.shape[1]
        self.L = np.random.uniform(low=0.1,high=0.9,size=(self.L_count,self.features))
        self.U = np.random.uniform(low=0.1,high=0.9,size=(self.features,self.U_count))
    
    def single_gradient(self,user_row,item_col,wrt_user_idx=None,wrt_item_idx=None):
        row = self.L[user_row,:]
        col = self.U[:,item_col]
        rank = float(self.data[user_row,item_col])
        next = float(np.dot(row,col))

        if wrt_user_idx != None:
            row_elem = float(col[wrt_user_idx]) 
            gradient = 2*(rank - next)*row_elem
        else:
            col_elem = float(row[wrt_item_idx])
            gradient = 2*(rank - next)*col_elem
        return gradient
                
    def train_model(self,learning_rate=0.1,iterations=700):   
        for c in range(iterations):
            for i in range(0,self.L_count):
                for j in range(0,self.features):
                    self.L[i,j] += learning_rate*(sum([self.single_gradient(user_row=i,item_col=col,wrt_user_idx=j) for col in range(0,self.U_count)])/self.U_count)
            for i in range(0,self.features):
                for j in range(0,self.U_count):
                    self.U[i,j] += learning_rate*sum([self.single_gradient(user_row=row,item_col=j,wrt_item_idx=i) for row in range(0,self.L_count)])/self.L_count

In [10]:
import numpy as np
# trying gradiant descent with 2 features
data = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]) # input matrix here
fac = matrix_factorization(data = data, features = 2) # number of features
fac.train_model(learning_rate=.1)
np.dot(fac.L,fac.U)

array([[0.99978015, 2.00119378, 2.99927853],
       [1.00024682, 1.99865976, 3.00080998],
       [0.99994619, 2.00029217, 2.99982342],
       [0.99982684, 2.00094025, 2.99943176],
       [0.9999308 , 2.00037577, 2.9997729 ],
       [1.00026004, 1.99858803, 3.00085333]])

In [12]:
# trying the same matrix with 13 features, it reaches the original matrix in this case
fac = matrix_factorization(data = data, features = 13)
fac.train_model(learning_rate=.1)
np.dot(fac.L,fac.U)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [19]:
# try your inputs here!
data = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]]) # input matrix here
features = 13 # change this integer to give different input values for number of features
fac = matrix_factorization(data = data, features = features)
fac.train_model(learning_rate=.1) #Adjust learning rate here
print("Number of features:", features)
print("Original Matrix:\n", data)
print("\nOutput Matrix:\n", np.dot(fac.L,fac.U))

Number of features: 13
Original Matrix:
 [[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

Output Matrix:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
